require('globals')
require('options')
require('keymaps')
require('autocmds')

require('lazy-setup')

-- https://stackoverflow.com/questions/15429236/how-to-check-if-a-module-exists-in-lua
local isModuleAvailable = function(name)
	if package.loaded[name] then
		return true
	else
		for _, searcher in ipairs(package.loaders) do
			local loader = searcher(name)
			if type(loader) == 'function' then
				package.preload[name] = loader
				return true
			end
		end
		return false
	end
end

-- custom plugins/runtime paths generated by nix
if isModuleAvailable('nix') then
	require('nix')
end
